name: flutter_application_instageram
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
hexcolor: ^3.0.1
dotted_border: ^2.0.0+2




flutter:

  uses-material-design: true

 
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # example:
  fonts:
    - family: GR
      fonts:
        - asset: fonts/GilroyRegular.ttf
          weight: 400

    - family: GM
      fonts:
        - asset: fonts/GilroyMedium.ttf
          weight: 500

    - family: GB
      fonts:
        - asset: fonts/GilroyBold.ttf
          weight: 700

    - family: GEB
      fonts:
        - asset: fonts/GilroyExtraBold.ttf
          weight: 800
          
    - family: GH
      fonts:
        - asset: fonts/GilroyHeavy.ttf
          weight: 900

    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf
          weight: 500 
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
